sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script: ./gradlew check

deploy:
  provider: releases
  api_key: 5eb80d564da98d8513bb48a1c1cd50dbe8e65f17
  file: build/distributions/elasticsearch-linear-regression*.zip
  skip_cleanup: true
  on:
    tags: true
