sudo: false
language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
script: ./gradlew check

deploy:
  provider: releases
  api_key: 383e51e8090b22a6f444ee92c0d72cddf3ff61ba
  file: build/distributions/elasticsearch-linear-regression*.zip
  skip_cleanup: true
  on:
    tags: true
